// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
<<<<<<< HEAD
show defaultTargetPlatform, kIsWeb, TargetPlatform;

=======
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
>>>>>>> bd07d5303f89c6336f5bb47fb3f1f526f7a7a6ee
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO1Elm-hTL3oBj_g6pFsY5fYdEGTMkQao',
    appId: '1:1090893062377:web:250f3aa4af520fabc3d078',
    messagingSenderId: '1090893062377',
    projectId: 'signspeak-85332',
    authDomain: 'signspeak-85332.firebaseapp.com',
    storageBucket: 'signspeak-85332.firebasestorage.app',
    measurementId: 'G-XHLPCTDSHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALiPm7pDDnjqZEc7A_JKYYUTFLwh2qfC8',
    appId: '1:1090893062377:android:76b215815099cbacc3d078',
    messagingSenderId: '1090893062377',
    projectId: 'signspeak-85332',
    storageBucket: 'signspeak-85332.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT2A72GSEvL66I20p98D7blTry-Tbpgco',
    appId: '1:1090893062377:ios:c05e5204042f07acc3d078',
    messagingSenderId: '1090893062377',
    projectId: 'signspeak-85332',
    storageBucket: 'signspeak-85332.firebasestorage.app',
    iosBundleId: 'com.example.signspeak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT2A72GSEvL66I20p98D7blTry-Tbpgco',
    appId: '1:1090893062377:ios:c05e5204042f07acc3d078',
    messagingSenderId: '1090893062377',
    projectId: 'signspeak-85332',
    storageBucket: 'signspeak-85332.firebasestorage.app',
    iosBundleId: 'com.example.signspeak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDO1Elm-hTL3oBj_g6pFsY5fYdEGTMkQao',
    appId: '1:1090893062377:web:1acc674289506499c3d078',
    messagingSenderId: '1090893062377',
    projectId: 'signspeak-85332',
    authDomain: 'signspeak-85332.firebaseapp.com',
    storageBucket: 'signspeak-85332.firebasestorage.app',
    measurementId: 'G-NN0CSXEHL4',
  );
}
